[project]
name = "interceptors-demo-mcpserver"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
